modLoader = "javafml"
loaderVersion = "[47,)"
license = "${license}"
issueTrackerURL="${mod_issue_url}"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${displayName}"
authors = "${authors}"
description = "${description}"
logoFile="pack.png" #optional
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://rosehearth.farm/MC_Mods/Compatemon/updates.json" #optional
#displayURL="${mod_homepage}"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.4.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "pehkui"
mandatory = false
versionRange = "[3.7.12,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "apotheosis"
mandatory = false
versionRange = "[7.2.2,)"
ordering = "NONE"
side = "BOTH"