modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT License"
issueTrackerURL="https://github.com/RosehearthFarms/Compatemon/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId = "compatemon" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Compatemon" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://rosehearth.farm/MC_Mods/CobblemonSizes/updates.json" #optional
#displayURL="https://rosehearth.farm/MC_Mods/CobblemonSizes" #optional
logoFile="logo.png" #optional
authors = "Gormottian" #optional
description = "Compatibility mod for cobblemon with large scale gameplay mods. Current only pehkui."
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.compatemon]] #optional
# the modid of the dependency
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[47,)" #mandatory
ordering = "NONE"
side = "BOTH"
# Here's another dependency
[[dependencies.compatemon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"